# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Method5

# Model Form Field configuration
form: $/mohsin/selectable/models/method5/fields.yaml

# Model Class name
modelClass: Mohsin\Selectable\Models\Method5

# Default redirect location
defaultRedirect: mohsin/selectable/method5

# Create page
create:
    title: Create Status List
    redirect: mohsin/selectable/method5/update/:id
    redirectClose: mohsin/selectable/method5

# Update page
update:
    title: Edit Status List
    redirect: mohsin/selectable/method5
    redirectClose: mohsin/selectable/method5

# Preview page
preview:
    title: Preview Status List
