# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Method4

# Model Form Field configuration
form: $/mohsin/selectable/models/method4/fields.yaml

# Model Class name
modelClass: Mohsin\Selectable\Models\Method4

# Default redirect location
defaultRedirect: mohsin/selectable/method4

# Create page
create:
    title: Create Status List
    redirect: mohsin/selectable/method4/update/:id
    redirectClose: mohsin/selectable/method4

# Update page
update:
    title: Edit Status List
    redirect: mohsin/selectable/method4
    redirectClose: mohsin/selectable/method4

# Preview page
preview:
    title: Preview Status List
